
import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 12,
    fontFamily: 'Helvetica',
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#4f46e5',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4f46e5', 
  },
  subtitle: {
    fontSize: 10,
    color: '#64748b',
  },
  statsContainer: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    padding: 15,
    borderRadius: 8,
    marginBottom: 20,
    justifyContent: 'space-between',
  },
  statBox: {
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1e293b',
    marginTop: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 5,
  },
  content: {
    marginBottom: 10,
    color: '#334155',
    textAlign: 'justify',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 9,
    color: '#94a3b8',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 10,
  },
});

// Helper to sanitize text (remove basic markdown symbols for cleaner plain text)
const cleanText = (text) => {
  if (!text) return '';
  return text
    .replace(/\*\*/g, '') // Remove bold markers
    .replace(/##/g, '') // Remove heading markers
    .replace(/\*/g, '')   // Remove italic/list markers (be careful with bullet points)
    .replace(/\[(.*?)\]\(.*?\)/g, '$1'); // Replace links with just text
};

const TutorPDFDocument = ({ data, selectedUser, userNamesMap }) => {
  const userName = userNamesMap[selectedUser] || selectedUser;
  const date = new Date().toLocaleDateString();

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        {/* Header */}
        <View style={styles.header}>
            <View>
                <Text style={styles.title}>AI DSA Tutor Report</Text>
                <Text style={styles.subtitle}>Personalized roadmap and analysis</Text>
            </View>
            <View style={{ alignItems: 'flex-end' }}>
                <Text style={styles.subtitle}>User: {userName}</Text>
                <Text style={styles.subtitle}>Date: {date}</Text>
            </View>
        </View>

        {/* Stats Snapshot */}
        {data && (
            <View style={styles.statsContainer}>
                <View style={styles.statBox}>
                    <Text style={styles.statLabel}>Total Solved</Text>
                    <Text style={styles.statValue}>{data.totalSolved}</Text>
                </View>
                <View style={styles.statBox}>
                    <Text style={styles.statLabel}>Global Ranking</Text>
                    <Text style={styles.statValue}>{data.ranking ? data.ranking.toLocaleString() : 'N/A'}</Text>
                </View>
                <View style={styles.statBox}>
                    <Text style={styles.statLabel}>Contribution</Text>
                    <Text style={styles.statValue}>{data.contributionPoint}</Text>
                </View>
                <View style={styles.statBox}>
                    <Text style={styles.statLabel}>Easy Solved</Text>
                    <Text style={styles.statValue}>{data.easySolved}</Text>
                </View>
            </View>
        )}

        {/* Analysis Content */}
        {data && data.tutorReply && (
            <View>
                <Text style={styles.sectionTitle}>Detailed Analysis</Text>
                <Text style={styles.content}>
                    {cleanText(data.tutorReply)}
                </Text>
            </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
            <Text>Generated by LeetCode Ranking App | AI DSA Tutor</Text>
        </View>

      </Page>
    </Document>
  );
};


export default TutorPDFDocument;

import PropTypes from 'prop-types';

TutorPDFDocument.propTypes = {
  data: PropTypes.shape({
    totalSolved: PropTypes.number,
    ranking: PropTypes.number,
    contributionPoint: PropTypes.number,
    easySolved: PropTypes.number,
    tutorReply: PropTypes.string,
  }),
  selectedUser: PropTypes.string,
  userNamesMap: PropTypes.object,
};
